### ISSUE TITLE
Severe thunderstorm warning for Madison County NY 

### ISSUE THREAD

**Issue by Romecityweather** [WeatherProvider/NationalWeatherService-Swift#15]
I’m sorry to hear that. I hope you are safe. I couldn’t find any severe thunderstorm warning for Madison County, NY at the moment [1](https://localconditions.com/weather-madison-county-new-york/ny0681/alerts.php)[2](https://www.willyweather.com/warnings/ny/madison-county.html). However, you can check the official website of the National Weather Service for the latest weather updates and warnings in your area [1](https://localconditions.com/weather-madison-county-new-york/ny0681/alerts.php). You can also download the NWS mobile app to receive alerts and warnings on your phone [2](https://www.willyweather.com/warnings/ny/madison-county.html).
Stay safe and take care! 😊

**Comment by Romecityweather** [comment]
I’m sorry to hear that. I hope you are safe. I couldn’t find any severe thunderstorm warning for Madison County, NY at the moment [1](https://localconditions.com/weather-madison-county-new-york/ny0681/alerts.php)[2](https://www.willyweather.com/warnings/ny/madison-county.html). However, you can check the official website of the National Weather Service for the latest weather updates and warnings in your area [1](https://localconditions.com/weather-madison-county-new-york/ny0681/alerts.php). You can also download the NWS mobile app to receive alerts and warnings on your phone [2](https://www.willyweather.com/warnings/ny/madison-county.html).
Stay safe and take care! 😊

**Comment by ualch9** [comment]
?
