### ISSUE TITLE
Error when attempting to add using Swift Package Manager

### ISSUE THREAD

**Issue by codger** [WeatherProvider/NationalWeatherService-Swift#3]
I was trying to install I get error
"because no versions of NationalWeatherService-Swift match the requirement 0.3.0 and root depends on NationalWeatherService-Swift 0.3.0, version solving failed."

I have tried using 0.0 and 0.3 as minimum parameters 

regards

John James
jjames@pacbell.net

**Comment by ualch9** [comment]
apologies, the tags were named incorrectly. i just fixed it, xcode should automatically detect version 0.3.0 now.
